name: Docker Image CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 设置 docker 环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # 编译并推送镜像到阿里云
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME_ALIYUN }} --password=${{ secrets.DOCKER_PASSWORD_ALIYUN }} registry.cn-hangzhou.aliyuncs.com
          cd navigator-web
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/ffget_dev/navigator-web:beta
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/ffget_dev/navigator-web:beta

      # 打印 docker 镜像 SHA256 Hash 值
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
