name: Docker Image CI

on:
  push:
    branches:
      - "master"

env:
  APP_LOCATION: "/"
  APP_VERSION: "latest"
  APP_NAME: "Docker"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      # 设置 docker 环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

        # 登录到阿里云容器镜像服务
      - name: Login to Ali Docker
        uses: docker/login-action@v1
        # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
        with:
          registry: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_HUB_PASSWORD }}

      # 构建镜像并上传到阿里云容器镜像仓库
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY_STORE }}:${{ env.APP_VERSION }}

      # 打印 docker 镜像 SHA256 Hash 值
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
